/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bd.Querys;
import bd.Sesion;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import controladores.cambioColor;
import static interfaces.vtnLogin.con;
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.StyledEditorKit;

/**
 *
 * @author david
 */
public class vtnAdminMenuUsuariosM extends javax.swing.JFrame {

    String idEmpleado = "";
    int xy, xx;
    boolean flagMedico = false;
    cambioColor cc = new cambioColor();

    /**
     * Creates new form vtnAdminAU
     */
    public vtnAdminMenuUsuariosM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLMinimizar = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLTitulo1 = new javax.swing.JLabel();
        jBModifica = new javax.swing.JButton();
        jCBRol = new javax.swing.JComboBox<>();
        jCBSexo = new javax.swing.JComboBox<>();
        jPNombre = new javax.swing.JPanel();
        jLNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jPFechaNac = new javax.swing.JPanel();
        jLFechaNac = new javax.swing.JLabel();
        jPAPaterno = new javax.swing.JPanel();
        jLAPaterno = new javax.swing.JLabel();
        jTFAPaterno = new javax.swing.JTextField();
        jPAMaterno = new javax.swing.JPanel();
        jLAMaterno = new javax.swing.JLabel();
        jTFAMaterno = new javax.swing.JTextField();
        jPTelefono = new javax.swing.JPanel();
        jLTelefono = new javax.swing.JLabel();
        jTFTelefono = new javax.swing.JTextField();
        jPEmail = new javax.swing.JPanel();
        jLEmail = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jPContra = new javax.swing.JPanel();
        jLContra1 = new javax.swing.JLabel();
        jPFContra1 = new javax.swing.JPasswordField();
        jPContra2 = new javax.swing.JPanel();
        jLContra2 = new javax.swing.JLabel();
        jPFContra2 = new javax.swing.JPasswordField();
        jPCurp = new javax.swing.JPanel();
        jLCURP = new javax.swing.JLabel();
        jTFCURP = new javax.swing.JTextField();
        jPSexo = new javax.swing.JPanel();
        jLSexo = new javax.swing.JLabel();
        jPDireccion = new javax.swing.JPanel();
        jLDireccion = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jPFacultad = new javax.swing.JPanel();
        jLFacu = new javax.swing.JLabel();
        jTFFacu = new javax.swing.JTextField();
        jPRol = new javax.swing.JPanel();
        jLRol = new javax.swing.JLabel();
        jPCedula = new javax.swing.JPanel();
        jLCedula = new javax.swing.JLabel();
        jTFCedula = new javax.swing.JTextField();
        jDCFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 35));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/minimizar-icon.png"))); // NOI18N
        jLMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMinimizarMouseClicked(evt);
            }
        });
        jPanel3.add(jLMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, 40));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/regreso.png"))); // NOI18N
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
        });
        jPanel3.add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 30, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLTitulo1.setText("Modificacion de usuarios");
        jPanel1.add(jLTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jBModifica.setBackground(new java.awt.Color(255, 204, 102));
        jBModifica.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBModifica.setText("Modificar");
        jBModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificaActionPerformed(evt);
            }
        });
        jBModifica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBModificaKeyPressed(evt);
            }
        });
        jPanel1.add(jBModifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 130, -1));

        jCBRol.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCBRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione rol", "Admin", "Medico", "Auxiliar" }));
        jCBRol.setToolTipText("");
        jCBRol.setEnabled(false);
        jCBRol.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBRolItemStateChanged(evt);
            }
        });
        jCBRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBRolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCBRolMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCBRolMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCBRolMouseReleased(evt);
            }
        });
        jCBRol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCBRolKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCBRolKeyReleased(evt);
            }
        });
        jPanel1.add(jCBRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 170, -1));

        jCBSexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCBSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione sexo", "Masculino", "Femenino" }));
        jCBSexo.setToolTipText("");
        jCBSexo.setEnabled(false);
        jCBSexo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBSexoItemStateChanged(evt);
            }
        });
        jCBSexo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBSexoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCBSexoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCBSexoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCBSexoMouseReleased(evt);
            }
        });
        jCBSexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCBSexoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCBSexoKeyReleased(evt);
            }
        });
        jPanel1.add(jCBSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 170, -1));

        jPNombre.setBackground(new java.awt.Color(255, 255, 255));
        jPNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPNombre.setEnabled(false);
        jPNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPNombreMouseEntered(evt);
            }
        });
        jPNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNombre.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLNombre.setText("Nombre:");
        jPNombre.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTFNombre.setBorder(null);
        jTFNombre.setEnabled(false);
        jTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNombreKeyTyped(evt);
            }
        });
        jPNombre.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 20));

        jPanel1.add(jPNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, 60));

        jPFechaNac.setBackground(new java.awt.Color(255, 255, 255));
        jPFechaNac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPFechaNac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLFechaNac.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLFechaNac.setText("Fecha de nacimiento:");
        jPFechaNac.add(jLFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 190, 30));

        jPAPaterno.setBackground(new java.awt.Color(255, 255, 255));
        jPAPaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPAPaterno.setEnabled(false);
        jPAPaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPAPaternoMouseEntered(evt);
            }
        });
        jPAPaterno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLAPaterno.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLAPaterno.setText("Apellido paterno:");
        jPAPaterno.add(jLAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFAPaterno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTFAPaterno.setBorder(null);
        jTFAPaterno.setEnabled(false);
        jTFAPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFAPaternoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFAPaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAPaternoKeyTyped(evt);
            }
        });
        jPAPaterno.add(jTFAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 20));

        jPanel1.add(jPAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 190, 60));

        jPAMaterno.setBackground(new java.awt.Color(255, 255, 255));
        jPAMaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPAMaterno.setEnabled(false);
        jPAMaterno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPAMaternoMouseEntered(evt);
            }
        });
        jPAMaterno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLAMaterno.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLAMaterno.setText("Apellido materno:");
        jPAMaterno.add(jLAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFAMaterno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTFAMaterno.setBorder(null);
        jTFAMaterno.setEnabled(false);
        jTFAMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFAMaternoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFAMaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAMaternoKeyTyped(evt);
            }
        });
        jPAMaterno.add(jTFAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 20));

        jPanel1.add(jPAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 190, 60));

        jPTelefono.setBackground(new java.awt.Color(255, 255, 255));
        jPTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPTelefono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTelefono.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLTelefono.setText("Teléfono:");
        jPTelefono.add(jLTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFTelefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTFTelefono.setBorder(null);
        jTFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFTelefonoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFTelefonoKeyTyped(evt);
            }
        });
        jPTelefono.add(jTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 20));

        jPanel1.add(jPTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 190, 60));

        jPEmail.setBackground(new java.awt.Color(255, 255, 255));
        jPEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPEmail.setEnabled(false);
        jPEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPEmailMouseEntered(evt);
            }
        });
        jPEmail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLEmail.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLEmail.setText("Email:");
        jPEmail.add(jLEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTFEmail.setBorder(null);
        jTFEmail.setEnabled(false);
        jTFEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFEmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFEmailKeyTyped(evt);
            }
        });
        jPEmail.add(jTFEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 20));

        jPanel1.add(jPEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 190, 60));

        jPContra.setBackground(new java.awt.Color(255, 255, 255));
        jPContra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPContra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLContra1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLContra1.setText("Contraseña:");
        jPContra.add(jLContra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPFContra1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPFContra1.setBorder(null);
        jPFContra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPFContra1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPFContra1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPFContra1KeyTyped(evt);
            }
        });
        jPContra.add(jPFContra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 20));

        jPanel1.add(jPContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 190, 60));

        jPContra2.setBackground(new java.awt.Color(255, 255, 255));
        jPContra2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPContra2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLContra2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLContra2.setText("Confirme contraseña:");
        jPContra2.add(jLContra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPFContra2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPFContra2.setBorder(null);
        jPFContra2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPFContra2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPFContra2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPFContra2KeyTyped(evt);
            }
        });
        jPContra2.add(jPFContra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 20));

        jPanel1.add(jPContra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 190, 60));

        jPCurp.setBackground(new java.awt.Color(255, 255, 255));
        jPCurp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPCurp.setEnabled(false);
        jPCurp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPCurpMouseEntered(evt);
            }
        });
        jPCurp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCURP.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLCURP.setText("CURP:");
        jPCurp.add(jLCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFCURP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTFCURP.setBorder(null);
        jTFCURP.setEnabled(false);
        jTFCURP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCURPActionPerformed(evt);
            }
        });
        jTFCURP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCURPKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFCURPKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCURPKeyTyped(evt);
            }
        });
        jPCurp.add(jTFCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 20));

        jPanel1.add(jPCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 190, 60));

        jPSexo.setBackground(new java.awt.Color(255, 255, 255));
        jPSexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPSexo.setEnabled(false);
        jPSexo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLSexo.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLSexo.setText("Sexo:");
        jPSexo.add(jLSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 190, 30));

        jPDireccion.setBackground(new java.awt.Color(255, 255, 255));
        jPDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPDireccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLDireccion.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLDireccion.setText("Dirección:");
        jPDireccion.add(jLDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFDireccion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTFDireccion.setBorder(null);
        jTFDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDireccionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFDireccionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFDireccionKeyTyped(evt);
            }
        });
        jPDireccion.add(jTFDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 20));

        jPanel1.add(jPDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 190, 60));

        jPFacultad.setBackground(new java.awt.Color(255, 255, 255));
        jPFacultad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPFacultad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPFacultadMouseEntered(evt);
            }
        });
        jPFacultad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLFacu.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLFacu.setText("Facultad de egreso:");
        jLFacu.setEnabled(false);
        jPFacultad.add(jLFacu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFFacu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTFFacu.setBorder(null);
        jTFFacu.setEnabled(false);
        jTFFacu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFFacuKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFFacuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFFacuKeyTyped(evt);
            }
        });
        jPFacultad.add(jTFFacu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 20));

        jPanel1.add(jPFacultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 190, 60));

        jPRol.setBackground(new java.awt.Color(255, 255, 255));
        jPRol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPRol.setEnabled(false);
        jPRol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLRol.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLRol.setText("Rol:");
        jPRol.add(jLRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 190, 30));

        jPCedula.setBackground(new java.awt.Color(255, 255, 255));
        jPCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPCedulaMouseEntered(evt);
            }
        });
        jPCedula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCedula.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLCedula.setText("Cedula:");
        jLCedula.setEnabled(false);
        jPCedula.add(jLCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFCedula.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTFCedula.setBorder(null);
        jTFCedula.setEnabled(false);
        jTFCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCedulaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFCedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCedulaKeyTyped(evt);
            }
        });
        jPCedula.add(jTFCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 20));

        jPanel1.add(jPCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 190, 60));

        jDCFecha.setDateFormatString("yyyy-MM-d");
        jDCFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDCFechaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jDCFechaMouseExited(evt);
            }
        });
        jDCFecha.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jDCFechaCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jDCFechanone(evt);
            }
        });
        jDCFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDCFechaPropertyChange(evt);
            }
        });
        jDCFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDCFechaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDCFechaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDCFechaKeyTyped(evt);
            }
        });
        jDCFecha.getDateEditor().addPropertyChangeListener(new PropertyChangeListener(){
            public void propertyChange(PropertyChangeEvent e) {
                //Aquí agregaremos la funcionalidad que queremos
                //por ejemplo al seleccionar una fecha le mostrare un diálogo con la fecha de hoy
                if (jDCFecha.getDate() == null)
                {
                    cc.cDefault(jPFechaNac, jLFechaNac);
                } else if (jDCFecha.getDate() != null)
                {
                    cc.cVerde(jPFechaNac, jLFechaNac);
                }
            }
        });
        jPanel1.add(jDCFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLMinimizarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseClicked
    {//GEN-HEADEREND:event_jLMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLMinimizarMouseClicked

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseClicked
    {//GEN-HEADEREND:event_jLCerrarMouseClicked
        Sesion.datosModifica.clear();
        this.dispose();
        new vtnAdminMenuUsuarios().setVisible(true);
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MouseDragged
    {//GEN-HEADEREND:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MousePressed
    {//GEN-HEADEREND:event_jPanel3MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        cc.cDefault(jTFTelefono, jLTelefono, jPTelefono);
        cc.cDisable(jLNombre, jLAPaterno, jLAMaterno, jLEmail,
                jLSexo, jLCURP, jLRol, jLCedula, jLFacu);

        cc.cDisable(jTFNombre, jTFAPaterno, jTFAMaterno, jTFEmail,
                jCBSexo, jTFCURP, jCBRol, jTFCedula, jTFFacu);

        cc.cDisable(jPNombre, jPAPaterno, jPAMaterno, jPEmail,
                jPSexo, jPCurp, jPRol, jPCedula, jPFacultad);

        idEmpleado = (String) Sesion.datosModifica.get(0);
        Querys q = new Querys();
        ArrayList<Object> mapeoData = new ArrayList<Object>();
        ArrayList<Object> mapeoData2 = new ArrayList<Object>();

        try {
            mapeoData = q.Seleccion(con, "*", "usuarios", "Id_empleado = " + idEmpleado, false);
        } catch (Exception e) {
            System.out.println("Error al obtener los datos del empelado" + idEmpleado + "..." + e);
        }

        int rolEmpleado = Integer.parseInt(((String) mapeoData.get(11)).trim());

        if (rolEmpleado == 2) {
            try {
                mapeoData2 = q.Seleccion(con, "*", "medicos", "Id_medico = " + idEmpleado, false);
            } catch (Exception e) {
                System.out.println("Error al obtener datos del medico..." + e);
            }

            jTFNombre.setText(((String) mapeoData.get(1)).trim());
            jTFAPaterno.setText(((String) mapeoData.get(2)).trim());
            jTFAMaterno.setText(((String) mapeoData.get(3)).trim());
            jTFTelefono.setText(((String) mapeoData.get(4)).trim());
            jTFEmail.setText(((String) mapeoData.get(5)).trim());
            jPFContra1.setText(((String) mapeoData.get(6)).trim());
            jPFContra2.setText(((String) mapeoData.get(6)).trim());
            jTFCURP.setText(((String) mapeoData.get(7)).trim());

            String sexo = ((String) mapeoData.get(8)).trim();
            if (sexo.equals("Masculino")) {
                jCBSexo.setSelectedIndex(1);
            } else if (sexo.equals("Femenino")) {
                jCBSexo.setSelectedIndex(2);
            }

            try {
                String fechaMap = ((String) mapeoData.get(9)).trim();
                Date fecha1 = new SimpleDateFormat("yyyy-MM-dd").parse(fechaMap);
                jDCFecha.setDate(fecha1);
            } catch (Exception e) {
                System.out.println("Error al comvetir la fecha..." + e);
            }

            jTFDireccion.setText(((String) mapeoData.get(10)).trim());

            int rolMap = Integer.parseInt(((String) mapeoData.get(11)).trim());

            jCBRol.setSelectedIndex(2);

            jTFCedula.setText(((String) mapeoData2.get(2)).trim());
            jTFFacu.setText(((String) mapeoData2.get(3)).trim());

        } else {
            jTFNombre.setText(((String) mapeoData.get(1)).trim());
            jTFAPaterno.setText(((String) mapeoData.get(2)).trim());
            jTFAMaterno.setText(((String) mapeoData.get(3)).trim());
            jTFTelefono.setText(((String) mapeoData.get(4)).trim());
            jTFEmail.setText(((String) mapeoData.get(5)).trim());
            jPFContra1.setText(((String) mapeoData.get(6)).trim());
            jPFContra2.setText(((String) mapeoData.get(6)).trim());
            jTFCURP.setText(((String) mapeoData.get(7)).trim());

            String sexo = ((String) mapeoData.get(8)).trim();
            if (sexo.equals("Masculino")) {
                jCBSexo.setSelectedIndex(1);
            } else if (sexo.equals("Femenino")) {
                jCBSexo.setSelectedIndex(2);
            }

            try {
                String fechaMap = ((String) mapeoData.get(9)).trim();
                Date fecha1 = new SimpleDateFormat("yyyy-MM-dd").parse(fechaMap);
                jDCFecha.setDate(fecha1);
            } catch (Exception e) {
                System.out.println("Error al comvetir la fecha..." + e);
            }

            jTFDireccion.setText(((String) mapeoData.get(10)).trim());

            int rolMap = Integer.parseInt(((String) mapeoData.get(11)).trim());

            if (rolMap == 1) {
                jCBRol.setSelectedIndex(1);
            } else if (rolMap == 3) {
                jCBRol.setSelectedIndex(3);
            }
        }
        CtrlInterfaz.selecciona(jTFTelefono);
    }//GEN-LAST:event_formWindowOpened

    private void jBModificaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jBModificaKeyPressed
    {//GEN-HEADEREND:event_jBModificaKeyPressed
        if (evt.getKeyChar() == '\n') {
            jBModificaActionPerformed(null);
        }
    }//GEN-LAST:event_jBModificaKeyPressed

    private void jBModificaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBModificaActionPerformed
    {//GEN-HEADEREND:event_jBModificaActionPerformed
        Querys q = new Querys();

        if (jLTelefono.getForeground().getRGB() == cc.getVerdeOscuro().getRGB()
                && jLContra1.getForeground().getRGB() == cc.getVerdeOscuro().getRGB()
                && jLContra2.getForeground().getRGB() == cc.getVerdeOscuro().getRGB()
                && jLFechaNac.getForeground().getRGB() == cc.getVerdeOscuro().getRGB()
                && jLDireccion.getForeground().getRGB() == cc.getVerdeOscuro().getRGB()) {

            Date fecha1 = jDCFecha.getDate();
            DateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String fecha2 = f.format(fecha1);

            String values = "'" + jTFTelefono.getText() + "',"
                    + "'" + jPFContra2.getText() + "',"
                    + "'" + fecha2 + "',"
                    + "'" + jTFDireccion.getText() + "'";

            String columnas1 = "Telefono,Contrasenia,Fecha_nacimiento,Direccion";

            if (Mensaje.pregunta(this, "¿Estas seguro de modificar el usuario?") == JOptionPane.YES_OPTION) {
                try {
                    q.Modificar(con, "usuarios", columnas1, values, "Id_empleado = " + idEmpleado);
                } catch (Exception e) {
                    System.out.println("Modificacion erronea" + e);
                }

                Mensaje.exito(this, "Se modifico el usuario correctamente");
                Sesion.datosModifica.clear();
                this.dispose();
                new vtnAdminMenuUsuarios().setVisible(true);
            } else {
                Mensaje.error(this, "No se hizo la modificacion");
            }

        } else {
            Mensaje.error(this, "Verifique que todos los campos esten en verde");
        }

    }//GEN-LAST:event_jBModificaActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowStateChanged
    {//GEN-HEADEREND:event_formWindowStateChanged

    }//GEN-LAST:event_formWindowStateChanged

    private void jCBRolItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBRolItemStateChanged

    }//GEN-LAST:event_jCBRolItemStateChanged

    private void jCBRolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBRolMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBRolMouseClicked

    private void jCBRolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBRolMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBRolMousePressed

    private void jCBRolMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBRolMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBRolMouseReleased

    private void jCBRolKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBRolKeyPressed

    }//GEN-LAST:event_jCBRolKeyPressed

    private void jCBRolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBRolKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBRolKeyReleased

    private void jCBSexoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBSexoItemStateChanged

    }//GEN-LAST:event_jCBSexoItemStateChanged

    private void jCBSexoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSexoMouseClicked

    }//GEN-LAST:event_jCBSexoMouseClicked

    private void jCBSexoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSexoMousePressed

    }//GEN-LAST:event_jCBSexoMousePressed

    private void jCBSexoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSexoMouseReleased

    }//GEN-LAST:event_jCBSexoMouseReleased

    private void jCBSexoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBSexoKeyPressed
        Validaciones.enter(this, evt, jDCFecha);
    }//GEN-LAST:event_jCBSexoKeyPressed

    private void jCBSexoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBSexoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBSexoKeyReleased

    private void jTFNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreKeyPressed

    }//GEN-LAST:event_jTFNombreKeyPressed

    private void jTFNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreKeyReleased

    }//GEN-LAST:event_jTFNombreKeyReleased

    private void jTFNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreKeyTyped
        Validaciones.validaAlfabeticos(evt);
        if (jTFNombre.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFNombreKeyTyped

    private void jTFAPaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAPaternoKeyPressed

    }//GEN-LAST:event_jTFAPaternoKeyPressed

    private void jTFAPaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAPaternoKeyReleased

    }//GEN-LAST:event_jTFAPaternoKeyReleased

    private void jTFAPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAPaternoKeyTyped
        Validaciones.validaAlfabeticos(evt);
        if (jTFAPaterno.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFAPaternoKeyTyped

    private void jTFAMaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAMaternoKeyPressed

    }//GEN-LAST:event_jTFAMaternoKeyPressed

    private void jTFAMaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAMaternoKeyReleased

    }//GEN-LAST:event_jTFAMaternoKeyReleased

    private void jTFAMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAMaternoKeyTyped
        Validaciones.validaAlfabeticos(evt);
        if (jTFAMaterno.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFAMaternoKeyTyped

    private void jTFTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTelefonoKeyPressed

    }//GEN-LAST:event_jTFTelefonoKeyPressed

    private void jTFTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTelefonoKeyReleased
        if (jTFTelefono.getText().isEmpty()) {
            cc.cDefault(jTFTelefono, jLTelefono, jPTelefono);
        } else if (jTFTelefono.getText().length() == 10) {
            cc.cVerde(jTFTelefono, jLTelefono, jPTelefono);
            Validaciones.enter(this, evt, jPFContra1);
        } else {
            cc.cRojo(jTFTelefono, jLTelefono, jPTelefono);
        }
    }//GEN-LAST:event_jTFTelefonoKeyReleased

    private void jTFTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTelefonoKeyTyped
        Validaciones.validaEntero(evt);
        if (jTFTelefono.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFTelefonoKeyTyped

    private void jTFEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFEmailKeyPressed

    }//GEN-LAST:event_jTFEmailKeyPressed

    private void jTFEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFEmailKeyReleased

    }//GEN-LAST:event_jTFEmailKeyReleased

    private void jTFEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFEmailKeyTyped
        if (jTFEmail.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFEmailKeyTyped

    private void jPFContra1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFContra1KeyPressed

    }//GEN-LAST:event_jPFContra1KeyPressed

    private void jPFContra1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFContra1KeyReleased
        if (jPFContra1.getText().isEmpty()) {
            cc.cDefault(jPFContra1, jLContra1, jPContra);
        } else if (jPFContra1.getText().length() >= 8) {
            cc.cVerde(jPFContra1, jLContra1, jPContra);
            Validaciones.enter(this, evt, jPFContra2);
        } else {
            cc.cRojo(jPFContra1, jLContra1, jPContra);
        }
    }//GEN-LAST:event_jPFContra1KeyReleased

    private void jPFContra1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFContra1KeyTyped
        if (jPFContra1.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jPFContra1KeyTyped

    private void jPFContra2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFContra2KeyPressed

    }//GEN-LAST:event_jPFContra2KeyPressed

    private void jPFContra2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFContra2KeyReleased
        if (jPFContra2.getText().isEmpty()) {
            cc.cDefault(jPFContra2, jLContra2, jPContra2);
        } else if (jPFContra2.getText().equals(jPFContra1.getText())) {
            cc.cVerde(jPFContra2, jLContra2, jPContra2);
            Validaciones.enter(this, evt, jDCFecha);
        } else {
            cc.cRojo(jPFContra2, jLContra2, jPContra2);
        }
    }//GEN-LAST:event_jPFContra2KeyReleased

    private void jPFContra2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFContra2KeyTyped

        if (jPFContra2.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jPFContra2KeyTyped

    private void jTFCURPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCURPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCURPActionPerformed

    private void jTFCURPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCURPKeyPressed

    }//GEN-LAST:event_jTFCURPKeyPressed

    private void jTFCURPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCURPKeyReleased

    }//GEN-LAST:event_jTFCURPKeyReleased

    private void jTFCURPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCURPKeyTyped
        Validaciones.validaAlfanumerico(evt);
        if (jTFCURP.getText().length() == 18) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFCURPKeyTyped

    private void jTFDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDireccionKeyPressed

    }//GEN-LAST:event_jTFDireccionKeyPressed

    private void jTFDireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDireccionKeyReleased
        if (jTFDireccion.getText().isEmpty()) {
            cc.cDefault(jLDireccion, jTFDireccion, jPDireccion);
        } else {
            cc.cVerde(jLDireccion, jTFDireccion, jPDireccion);
            Validaciones.enter(this, evt, jBModifica);
        }
    }//GEN-LAST:event_jTFDireccionKeyReleased

    private void jTFDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDireccionKeyTyped
        Validaciones.validaAlfanumerico(evt);
        if (jTFDireccion.getText().length() == 180) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFDireccionKeyTyped

    private void jTFFacuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFFacuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFFacuKeyPressed

    private void jTFFacuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFFacuKeyReleased

    }//GEN-LAST:event_jTFFacuKeyReleased

    private void jTFFacuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFFacuKeyTyped
        Validaciones.validaAlfanumerico(evt);
        if (jTFFacu.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFFacuKeyTyped

    private void jPFacultadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPFacultadMouseEntered
        if (!jTFFacu.isEnabled()) {
            try {
                jPFacultad.setCursor(Cursor.getSystemCustomCursor("Invalid.32x32"));
            } catch (AWTException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            } catch (HeadlessException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jPFacultad.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_jPFacultadMouseEntered

    private void jTFCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCedulaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCedulaKeyPressed

    private void jTFCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCedulaKeyReleased

    }//GEN-LAST:event_jTFCedulaKeyReleased

    private void jTFCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCedulaKeyTyped
        Validaciones.validaAlfanumerico(evt);
        if (jTFCedula.getText().length() == 8) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFCedulaKeyTyped

    private void jPCedulaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPCedulaMouseEntered
        if (!jTFCedula.isEnabled()) {
            try {
                jPCedula.setCursor(Cursor.getSystemCustomCursor("Invalid.32x32"));
            } catch (AWTException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            } catch (HeadlessException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jPCedula.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_jPCedulaMouseEntered

    private void jDCFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDCFechaMouseClicked

    }//GEN-LAST:event_jDCFechaMouseClicked

    private void jDCFechaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDCFechaMouseExited

    }//GEN-LAST:event_jDCFechaMouseExited

    private void jDCFechaCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jDCFechaCaretPositionChanged

    }//GEN-LAST:event_jDCFechaCaretPositionChanged

    private void jDCFechanone(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jDCFechanone

    }//GEN-LAST:event_jDCFechanone

    private void jDCFechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDCFechaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDCFechaPropertyChange

    private void jDCFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDCFechaKeyPressed
        Validaciones.enter(this, evt, jTFDireccion);
    }//GEN-LAST:event_jDCFechaKeyPressed

    private void jDCFechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDCFechaKeyReleased

    }//GEN-LAST:event_jDCFechaKeyReleased

    private void jDCFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDCFechaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jDCFechaKeyTyped

    private void jPNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPNombreMouseEntered
        if (!jTFNombre.isEnabled()) {
            try {
                jPNombre.setCursor(Cursor.getSystemCustomCursor("Invalid.32x32"));
            } catch (AWTException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            } catch (HeadlessException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jPNombre.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_jPNombreMouseEntered

    private void jPAPaternoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAPaternoMouseEntered
        if (!jTFAPaterno.isEnabled()) {
            try {
                jPAPaterno.setCursor(Cursor.getSystemCustomCursor("Invalid.32x32"));
            } catch (AWTException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            } catch (HeadlessException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jPAPaterno.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_jPAPaternoMouseEntered

    private void jPAMaternoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPAMaternoMouseEntered
        if (!jTFAMaterno.isEnabled()) {
            try {
                jPAMaterno.setCursor(Cursor.getSystemCustomCursor("Invalid.32x32"));
            } catch (AWTException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            } catch (HeadlessException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jPAMaterno.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_jPAMaternoMouseEntered

    private void jPEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPEmailMouseEntered
        if (!jTFEmail.isEnabled()) {
            try {
                jPEmail.setCursor(Cursor.getSystemCustomCursor("Invalid.32x32"));
            } catch (AWTException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            } catch (HeadlessException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jPEmail.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_jPEmailMouseEntered

    private void jPCurpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPCurpMouseEntered
        if (!jTFCURP.isEnabled()) {
            try {
                jPCurp.setCursor(Cursor.getSystemCustomCursor("Invalid.32x32"));
            } catch (AWTException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            } catch (HeadlessException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jPCurp.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_jPCurpMouseEntered

    private void jCBSexoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBSexoMouseEntered
        if (!jCBSexo.isEnabled()) {
            try {
                jCBSexo.setCursor(Cursor.getSystemCustomCursor("Invalid.32x32"));
            } catch (AWTException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            } catch (HeadlessException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jCBSexo.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_jCBSexoMouseEntered

    private void jCBRolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBRolMouseEntered
        if (!jCBRol.isEnabled()) {
            try {
                jCBRol.setCursor(Cursor.getSystemCustomCursor("Invalid.32x32"));
            } catch (AWTException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            } catch (HeadlessException ex) {
                Logger.getLogger(vtnAdminMenuUsuariosA.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jCBRol.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_jCBRolMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMenuUsuariosM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMenuUsuariosM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMenuUsuariosM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMenuUsuariosM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnAdminMenuUsuariosM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBModifica;
    private javax.swing.JComboBox<String> jCBRol;
    private javax.swing.JComboBox<String> jCBSexo;
    private com.toedter.calendar.JDateChooser jDCFecha;
    private javax.swing.JLabel jLAMaterno;
    private javax.swing.JLabel jLAPaterno;
    private javax.swing.JLabel jLCURP;
    private javax.swing.JLabel jLCedula;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLContra1;
    private javax.swing.JLabel jLContra2;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLFacu;
    private javax.swing.JLabel jLFechaNac;
    private javax.swing.JLabel jLMinimizar;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLRol;
    private javax.swing.JLabel jLSexo;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JLabel jLTitulo1;
    private javax.swing.JPanel jPAMaterno;
    private javax.swing.JPanel jPAPaterno;
    private javax.swing.JPanel jPCedula;
    private javax.swing.JPanel jPContra;
    private javax.swing.JPanel jPContra2;
    private javax.swing.JPanel jPCurp;
    private javax.swing.JPanel jPDireccion;
    private javax.swing.JPanel jPEmail;
    private javax.swing.JPasswordField jPFContra1;
    private javax.swing.JPasswordField jPFContra2;
    private javax.swing.JPanel jPFacultad;
    private javax.swing.JPanel jPFechaNac;
    private javax.swing.JPanel jPNombre;
    private javax.swing.JPanel jPRol;
    private javax.swing.JPanel jPSexo;
    private javax.swing.JPanel jPTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTFAMaterno;
    private javax.swing.JTextField jTFAPaterno;
    private javax.swing.JTextField jTFCURP;
    private javax.swing.JTextField jTFCedula;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFFacu;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFTelefono;
    // End of variables declaration//GEN-END:variables
}
