/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bd.Querys;
import bd.Autocomplete;
import bd.Sesion;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import com.mxrck.autocompleter.TextAutoCompleter;
import com.sun.org.apache.bcel.internal.classfile.JavaClass;
import controladores.cambioColor;
import static interfaces.vtnLogin.con;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.text.StyledEditorKit;
import jdk.nashorn.internal.runtime.arrays.ArrayLikeIterator;

/**
 *
 * @author david
 */
public class vtnAdminMenuBodegaA extends javax.swing.JFrame {

    int xy, xx;
    TextAutoCompleter ac;
    vtnAdminMenuProductosPOPUP menuPOPUP = new vtnAdminMenuProductosPOPUP();
    cambioColor cc = new cambioColor();

    /**
     * Creates new form vtnAdminAU
     */
    public vtnAdminMenuBodegaA() {
        initComponents();
        ac = new TextAutoCompleter(jTFProducto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLMinimizar = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLTitulo1 = new javax.swing.JLabel();
        jBAlta = new javax.swing.JButton();
        jBLimpia = new javax.swing.JButton();
        jPProducto = new javax.swing.JPanel();
        jLIDProducto = new javax.swing.JLabel();
        jTFProducto = new javax.swing.JTextField();
        jLSearch = new javax.swing.JLabel();
        jPCantidad = new javax.swing.JPanel();
        jLCantidad = new javax.swing.JLabel();
        jTFCantidad = new javax.swing.JTextField();
        jPProveedor = new javax.swing.JPanel();
        jLIDProveedor = new javax.swing.JLabel();
        jLProveedor = new javax.swing.JLabel();
        jPAMaterno = new javax.swing.JPanel();
        jLAMRepart = new javax.swing.JLabel();
        jTFAMRepart = new javax.swing.JTextField();
        jPRepartidor = new javax.swing.JPanel();
        jLNombreRepart = new javax.swing.JLabel();
        jTFNombreRepart = new javax.swing.JTextField();
        jPAPaterno = new javax.swing.JPanel();
        jLAPRepart = new javax.swing.JLabel();
        jTFAPRepart = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 35));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/minimizar-icon.png"))); // NOI18N
        jLMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMinimizarMouseClicked(evt);
            }
        });
        jPanel3.add(jLMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 40));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/regreso.png"))); // NOI18N
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
        });
        jPanel3.add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 30, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLTitulo1.setText("Recibir productos en bodega");
        jPanel2.add(jLTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jBAlta.setText("Recibir pedido");
        jBAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAltaActionPerformed(evt);
            }
        });
        jPanel2.add(jBAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        jBLimpia.setText("Limpiar");
        jBLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiaActionPerformed(evt);
            }
        });
        jPanel2.add(jBLimpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 110, -1));

        jPProducto.setBackground(new java.awt.Color(255, 255, 255));
        jPProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLIDProducto.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLIDProducto.setText("Producto:");
        jPProducto.add(jLIDProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFProducto.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTFProducto.setBorder(null);
        jTFProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFProductoActionPerformed(evt);
            }
        });
        jTFProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFProductoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFProductoKeyTyped(evt);
            }
        });
        jPProducto.add(jTFProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 20));

        jLSearch.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLSearch.setText("  Search");
        jLSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSearchMouseClicked(evt);
            }
        });
        jPProducto.add(jLSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 50, -1));

        jPanel2.add(jPProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 210, 50));

        jPCantidad.setBackground(new java.awt.Color(255, 255, 255));
        jPCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPCantidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCantidad.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLCantidad.setText("Cantidad:");
        jPCantidad.add(jLCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFCantidad.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTFCantidad.setBorder(null);
        jTFCantidad.setDoubleBuffered(true);
        jTFCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCantidadKeyTyped(evt);
            }
        });
        jPCantidad.add(jTFCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 20));

        jPanel2.add(jPCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 210, 50));

        jPProveedor.setBackground(new java.awt.Color(255, 255, 255));
        jPProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLIDProveedor.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLIDProveedor.setText("Proveedor:");
        jPProveedor.add(jLIDProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLProveedor.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jPProveedor.add(jLProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 20));

        jPanel2.add(jPProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 210, 50));

        jPAMaterno.setBackground(new java.awt.Color(255, 255, 255));
        jPAMaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPAMaterno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLAMRepart.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLAMRepart.setText("Apellido Materno del repartidor:");
        jPAMaterno.add(jLAMRepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFAMRepart.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTFAMRepart.setBorder(null);
        jTFAMRepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAMRepartActionPerformed(evt);
            }
        });
        jTFAMRepart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFAMRepartKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFAMRepartKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAMRepartKeyTyped(evt);
            }
        });
        jPAMaterno.add(jTFAMRepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 20));

        jPanel2.add(jPAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 210, 50));

        jPRepartidor.setBackground(new java.awt.Color(255, 255, 255));
        jPRepartidor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPRepartidor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNombreRepart.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLNombreRepart.setText("Nombre del repartidor:");
        jPRepartidor.add(jLNombreRepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFNombreRepart.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTFNombreRepart.setBorder(null);
        jTFNombreRepart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNombreRepartKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFNombreRepartKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNombreRepartKeyTyped(evt);
            }
        });
        jPRepartidor.add(jTFNombreRepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 20));

        jPanel2.add(jPRepartidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 210, 50));

        jPAPaterno.setBackground(new java.awt.Color(255, 255, 255));
        jPAPaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPAPaterno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLAPRepart.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLAPRepart.setText("Apellido Paterno del repartidor:");
        jPAPaterno.add(jLAPRepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTFAPRepart.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jTFAPRepart.setBorder(null);
        jTFAPRepart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFAPRepartKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFAPRepartKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAPRepartKeyTyped(evt);
            }
        });
        jPAPaterno.add(jTFAPRepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 20));

        jPanel2.add(jPAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 210, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 550, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLMinimizarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseClicked
    {//GEN-HEADEREND:event_jLMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLMinimizarMouseClicked

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseClicked
    {//GEN-HEADEREND:event_jLCerrarMouseClicked
        this.dispose();
        new vtnAdminMenuBodega(Integer.parseInt((String) Sesion.datosUsuario.get(11))).setVisible(true);
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MouseDragged
    {//GEN-HEADEREND:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MousePressed
    {//GEN-HEADEREND:event_jPanel3MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        Querys q = new Querys();
        ArrayList<Object> mapeoProductos = new ArrayList<Object>();
        ArrayList<Object> mapeoProductosF = new ArrayList<Object>();

        try {
            mapeoProductos = q.Seleccion(con, "Id_medicamento, Nombre_generico", "medicamentos",
                    "Caducidad >= CURDATE()", false);
            int constant = mapeoProductos.size() / 2;
            int id;
            for (int i = 0; i < constant; i++) {
                String producto = ((String) mapeoProductos.get(1)).trim() + "." + ((String) mapeoProductos.get(0)).trim();
                mapeoProductosF.add(producto);
                mapeoProductos.remove(0);
                mapeoProductos.remove(0);
            }

            for (int i = 0; i < mapeoProductosF.size(); i++) {
                ac.addItem(((String) mapeoProductosF.get(i)).trim());
            }
        } catch (Exception e) {
            System.out.println("Error al consultar productos..." + e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowStateChanged(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowStateChanged
    {//GEN-HEADEREND:event_formWindowStateChanged

    }//GEN-LAST:event_formWindowStateChanged

    private void jBAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBAltaActionPerformed
    {//GEN-HEADEREND:event_jBAltaActionPerformed
        Querys q = new Querys();
        ArrayList<Object> mapBodega = new ArrayList<Object>();
        ArrayList<Object> existencia = new ArrayList<Object>();

        if (jLIDProducto.getForeground().getRGB() == cc.getVerdeOscuro().getRGB()
                && jLIDProveedor.getForeground().getRGB() == cc.getVerdeOscuro().getRGB()
                && jLCantidad.getForeground().getRGB() == cc.getVerdeOscuro().getRGB()
                && jLNombreRepart.getForeground().getRGB() == cc.getVerdeOscuro().getRGB()
                && jLAPRepart.getForeground().getRGB() == cc.getVerdeOscuro().getRGB()
                && jLAMRepart.getForeground().getRGB() == cc.getVerdeOscuro().getRGB()) {

            try {
                mapBodega = q.Seleccion(con, "MAX(Id_historial)", "bodega", "", true);
            } catch (Exception e) {
                System.out.println("consulta max id historial erronea" + e);
            }

            int idFinal = Integer.parseInt((String) mapBodega.get(0)) + 1;

            Date fecha = new Date();
            fecha.getDate();
            DateFormat f1 = new SimpleDateFormat("yyyy-MM-dd");
            DateFormat f2 = new SimpleDateFormat("hh:mm:ss");
            String fechaF = f1.format(fecha);
            String horaF = f2.format(fecha);
            System.out.println(fechaF);
            System.out.println(horaF);
            String idProd = jTFProducto.getText();
            String[] parts = idProd.split("\\.");
            String part1 = parts[0];
            String part2 = parts[1];

            try {
                existencia = q.Seleccion(con, "Existencia", "medicamentos",
                        "Id_medicamento = " + part2, false);
            } catch (Exception e) {
                System.out.println("Error al consultar existencia dle producto a actualizar..." + e);
            }
            int existenciaFinal = Integer.parseInt((String) existencia.get(0)) + Integer.parseInt((String) jTFCantidad.getText());

            String values = "'" + idFinal + "',"
                    + "'" + Sesion.datosUsuario.get(0) + "',"
                    + "'" + part2 + "',"
                    + "'" + jTFCantidad.getText() + "',"
                    + "'" + jTFNombreRepart.getText() + "',"
                    + "'" + jTFAPRepart.getText() + "',"
                    + "'" + jTFAMRepart.getText() + "',"
                    + "'" + fechaF + "',"
                    + "'" + horaF + "'";
            String campos = "Existencia";
            String values2 = "'" + existenciaFinal + "'";

            if (Mensaje.pregunta(this, "¿Estas seguro que deseas recibir el pedido en bodega?") == JOptionPane.YES_OPTION) {
                try {
                    q.Insertar(con, "bodega", values);

                } catch (Exception e) {
                    System.out.println("insercion erronea en bodega..." + e);
                }

                try {

                    q.Modificar(con, "medicamentos", campos, values2,
                            "Id_medicamento=" + part2);

                } catch (Exception e) {
                    System.out.println("actualizacion erronea en medicamnetos..." + e);
                }

                Mensaje.exito(this, "Se registro correctamente el pedido y se actualizo el stock");
                jBLimpiaActionPerformed(null);
            } else {
                Mensaje.error(this, "No se dio el registro del pedido");
            }
        } else {
            Mensaje.error(this, "Verifique que todos los campos esten en verde");
        }

        menuPOPUP.dispose();
    }//GEN-LAST:event_jBAltaActionPerformed

    private void jBLimpiaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBLimpiaActionPerformed
    {//GEN-HEADEREND:event_jBLimpiaActionPerformed
        CtrlInterfaz.limpia(jTFProducto, jTFCantidad, jTFNombreRepart,
                jTFAPRepart, jTFAMRepart, jLProveedor);
        jLProveedor.setText("");

        cc.cDefault(jPProducto, jPProveedor, jPCantidad, jPRepartidor, jPAPaterno, jPAMaterno,
                jLIDProducto, jLIDProveedor, jLCantidad, jLNombreRepart, jLAPRepart, jLAMRepart,
                jTFProducto, jLProveedor, jTFCantidad, jTFNombreRepart, jTFAMRepart, jTFAPRepart);

        CtrlInterfaz.selecciona(jTFProducto);
    }//GEN-LAST:event_jBLimpiaActionPerformed

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved

    }//GEN-LAST:event_jPanel2MouseMoved

    private void jTFProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFProductoKeyPressed

    }//GEN-LAST:event_jTFProductoKeyPressed

    private void jTFCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCantidadKeyPressed
        Querys q = new Querys();
        ArrayList<Object> proveedor = new ArrayList<Object>();

        try {
            String producto = jTFProducto.getText();

            if (producto.contains(".")) {
                String[] parts = producto.split("\\.");
                String part1 = parts[0];
                String part2 = parts[1];
                try {
                    proveedor = q.Seleccion(con, "Id_proveedor", "medicamentos",
                            "Id_medicamento='" + part2 + "'", false);
                } catch (Exception e) {
                    System.out.println("");
                }

                String idProv = (String) proveedor.get(0);
                try {
                    proveedor = q.Seleccion(con, "NombreProveedor", "proveedores",
                            "Id_proveedor='" + idProv + "'", false);
                } catch (Exception e) {
                    System.out.println("Error al intentar obtner nombre proveedro..." + e);
                }

                if (!proveedor.isEmpty()) {
                    jLProveedor.setText(((String) proveedor.get(0)).trim());

                    cc.cVerde(jPProveedor, jLProveedor, jLIDProveedor);
                } else {
                    cc.cDefault(jPProveedor, jLProveedor, jLIDProveedor);
                }
            } else {
                cc.cRojo(jPProveedor, jLProveedor, jLIDProveedor);
            }

        } catch (Exception e) {
            System.out.println("Error ya que no hay datos en proveedormap..." + e);
        }
    }//GEN-LAST:event_jTFCantidadKeyPressed

    private void jTFNombreRepartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreRepartKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreRepartKeyPressed

    private void jTFAPRepartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAPRepartKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAPRepartKeyPressed

    private void jTFAMRepartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAMRepartKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAMRepartKeyPressed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        menuPOPUP.dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jTFProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFProductoKeyReleased

        if (jTFProducto.getText().isEmpty()) {
            //colores cajas
            cc.cDefault(jPProducto, jTFProducto, jLIDProducto,
                    jPProveedor, jLProveedor, jLIDProveedor);
            jLProveedor.setText("");
        } else {
            //colores cajas
            cc.cVerde(jPProducto, jTFProducto, jLIDProducto, jTFProducto);
            Validaciones.enter(this, evt, jTFCantidad);
        }
    }//GEN-LAST:event_jTFProductoKeyReleased

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved

    }//GEN-LAST:event_formMouseMoved

    private void jTFCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCantidadKeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_jTFCantidadKeyTyped

    private void jTFCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCantidadKeyReleased
        if (jTFCantidad.getText().isEmpty()) {
            //colores cajas
            cc.cDefault(jPCantidad, jTFCantidad, jLCantidad);

        } else if (jTFCantidad.getText().length() <= 5) {
            //colores cajas
            cc.cVerde(jPCantidad, jTFCantidad, jLCantidad);

            Validaciones.enter(this, evt, jTFNombreRepart);
        } else {
            //colores cajas
            cc.cRojo(jPCantidad, jTFCantidad, jLCantidad);
        }
    }//GEN-LAST:event_jTFCantidadKeyReleased

    private void jTFProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFProductoKeyTyped
        Validaciones.validaAlfanumerico(evt);
    }//GEN-LAST:event_jTFProductoKeyTyped

    private void jTFNombreRepartKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreRepartKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_jTFNombreRepartKeyTyped

    private void jTFAPRepartKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAPRepartKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_jTFAPRepartKeyTyped

    private void jTFAMRepartKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAMRepartKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_jTFAMRepartKeyTyped

    private void jTFNombreRepartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreRepartKeyReleased
        if (jTFNombreRepart.getText().isEmpty()) {
            //colores cajas
            cc.cDefault(jPRepartidor, jTFNombreRepart, jLNombreRepart);
        } else {
            //colores cajas
            cc.cVerde(jPRepartidor, jTFNombreRepart, jLNombreRepart);
            Validaciones.enter(this, evt, jTFAPRepart);
        }
    }//GEN-LAST:event_jTFNombreRepartKeyReleased

    private void jTFAPRepartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAPRepartKeyReleased
        if (jTFAPRepart.getText().isEmpty()) {
            cc.cDefault(jPAPaterno, jTFAPRepart, jLAPRepart);
        } else {
            cc.cVerde(jPAPaterno, jTFAPRepart, jLAPRepart);
            Validaciones.enter(this, evt, jTFAMRepart);
        }
    }//GEN-LAST:event_jTFAPRepartKeyReleased

    private void jTFAMRepartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAMRepartKeyReleased
        if (jTFAMRepart.getText().isEmpty()) {
            cc.cDefault(jPAMaterno, jTFAMRepart, jLAMRepart);
        } else {
            cc.cVerde(jPAMaterno, jTFAMRepart, jLAMRepart);
            Validaciones.enter(this, evt, jBAlta);
        }
    }//GEN-LAST:event_jTFAMRepartKeyReleased

    private void jTFProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFProductoActionPerformed

    private void jLSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSearchMouseClicked
        menuPOPUP.setVisible(true);
    }//GEN-LAST:event_jLSearchMouseClicked

    private void jTFAMRepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAMRepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAMRepartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMenuBodegaA.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMenuBodegaA.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMenuBodegaA.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMenuBodegaA.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnAdminMenuBodegaA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlta;
    private javax.swing.JButton jBLimpia;
    private javax.swing.JLabel jLAMRepart;
    private javax.swing.JLabel jLAPRepart;
    private javax.swing.JLabel jLCantidad;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLIDProducto;
    private javax.swing.JLabel jLIDProveedor;
    private javax.swing.JLabel jLMinimizar;
    private javax.swing.JLabel jLNombreRepart;
    private javax.swing.JLabel jLProveedor;
    private javax.swing.JLabel jLSearch;
    private javax.swing.JLabel jLTitulo1;
    private javax.swing.JPanel jPAMaterno;
    private javax.swing.JPanel jPAPaterno;
    private javax.swing.JPanel jPCantidad;
    private javax.swing.JPanel jPProducto;
    private javax.swing.JPanel jPProveedor;
    private javax.swing.JPanel jPRepartidor;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTFAMRepart;
    private javax.swing.JTextField jTFAPRepart;
    private javax.swing.JTextField jTFCantidad;
    private javax.swing.JTextField jTFNombreRepart;
    private javax.swing.JTextField jTFProducto;
    // End of variables declaration//GEN-END:variables
}
