/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bd.Querys;
import bd.Sesion;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import static interfaces.vtnLogin.con;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.StyledEditorKit;

/**
 *
 * @author david
 */
public class vtnAdminMenuUsuariosM extends javax.swing.JFrame {

    String idEmpleado = "";
    int xy, xx;
    boolean flagMedico = false;

    /**
     * Creates new form vtnAdminAU
     */
    public vtnAdminMenuUsuariosM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLMinimizar = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCBRol = new javax.swing.JComboBox<>();
        jLRol = new javax.swing.JLabel();
        jLTitulo1 = new javax.swing.JLabel();
        jLAPaterno = new javax.swing.JLabel();
        jTFAPaterno = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLAMaterno = new javax.swing.JLabel();
        jTFAMaterno = new javax.swing.JTextField();
        jTFTelefono = new javax.swing.JTextField();
        jLTelefono = new javax.swing.JLabel();
        jLEmail = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jLContra1 = new javax.swing.JLabel();
        jLCURP = new javax.swing.JLabel();
        jTFCURP = new javax.swing.JTextField();
        jLSexo = new javax.swing.JLabel();
        jCBSexo = new javax.swing.JComboBox<>();
        jLFechaNac = new javax.swing.JLabel();
        jDCFecha = new com.toedter.calendar.JDateChooser();
        jLDireccion = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jBModifica = new javax.swing.JButton();
        jPFContra1 = new javax.swing.JPasswordField();
        jLContra2 = new javax.swing.JLabel();
        jPFContra2 = new javax.swing.JPasswordField();
        jLCedula = new javax.swing.JLabel();
        jTFCedula = new javax.swing.JTextField();
        jLFacu = new javax.swing.JLabel();
        jTFFacu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 35));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/minimizar-icon.png"))); // NOI18N
        jLMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMinimizarMouseClicked(evt);
            }
        });
        jPanel3.add(jLMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, 40));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/regreso.png"))); // NOI18N
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
        });
        jPanel3.add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 30, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBRol.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCBRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione rol", "Admin", "Medico", "Auxiliar" }));
        jCBRol.setToolTipText("");
        jCBRol.setEnabled(false);
        jCBRol.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBRolItemStateChanged(evt);
            }
        });
        jCBRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBRolMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCBRolMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCBRolMouseReleased(evt);
            }
        });
        jCBRol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCBRolKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCBRolKeyReleased(evt);
            }
        });
        jPanel1.add(jCBRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 160, -1));

        jLRol.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLRol.setText("Rol:");
        jPanel1.add(jLRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        jLTitulo1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLTitulo1.setText("Modificacion de usuarios");
        jPanel1.add(jLTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLAPaterno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLAPaterno.setText("Apellido paterno:");
        jPanel1.add(jLAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jTFAPaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFAPaterno.setEnabled(false);
        jTFAPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFAPaternoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFAPaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAPaternoKeyTyped(evt);
            }
        });
        jPanel1.add(jTFAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, -1));

        jLNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLNombre.setText("Nombre:");
        jPanel1.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jTFNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFNombre.setEnabled(false);
        jTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNombreKeyTyped(evt);
            }
        });
        jPanel1.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 160, -1));

        jLAMaterno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLAMaterno.setText("Apellido materno:");
        jPanel1.add(jLAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jTFAMaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFAMaterno.setEnabled(false);
        jTFAMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFAMaternoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFAMaternoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAMaternoKeyTyped(evt);
            }
        });
        jPanel1.add(jTFAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 160, -1));

        jTFTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFTelefonoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(jTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 160, -1));

        jLTelefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLTelefono.setText("Teléfono:");
        jPanel1.add(jLTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLEmail.setText("Email:");
        jPanel1.add(jLEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jTFEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFEmail.setEnabled(false);
        jTFEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFEmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFEmailKeyTyped(evt);
            }
        });
        jPanel1.add(jTFEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 160, -1));

        jLContra1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLContra1.setText("Contraseña:");
        jPanel1.add(jLContra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jLCURP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLCURP.setText("CURP:");
        jPanel1.add(jLCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jTFCURP.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFCURP.setEnabled(false);
        jTFCURP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCURPActionPerformed(evt);
            }
        });
        jTFCURP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCURPKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFCURPKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCURPKeyTyped(evt);
            }
        });
        jPanel1.add(jTFCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 160, -1));

        jLSexo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLSexo.setText("Sexo:");
        jPanel1.add(jLSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jCBSexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jCBSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione sexo", "Masculino", "Femenino" }));
        jCBSexo.setToolTipText("");
        jCBSexo.setEnabled(false);
        jCBSexo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBSexoItemStateChanged(evt);
            }
        });
        jCBSexo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBSexoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCBSexoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCBSexoMouseReleased(evt);
            }
        });
        jCBSexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCBSexoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCBSexoKeyReleased(evt);
            }
        });
        jPanel1.add(jCBSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 160, -1));

        jLFechaNac.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLFechaNac.setText("Fecha de nacimiento:");
        jPanel1.add(jLFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jDCFecha.setDateFormatString("yyyy-MM-d");
        jDCFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDCFechaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jDCFechaMouseExited(evt);
            }
        });
        jDCFecha.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jDCFechaCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                none(evt);
            }
        });
        jDCFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDCFechaPropertyChange(evt);
            }
        });
        jDCFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDCFechaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDCFechaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDCFechaKeyTyped(evt);
            }
        });
        jDCFecha.getDateEditor().addPropertyChangeListener(new PropertyChangeListener(){
            public void propertyChange(PropertyChangeEvent e) {
                //Aquí agregaremos la funcionalidad que queremos
                //por ejemplo al seleccionar una fecha le mostrare un diálogo con la fecha de hoy
                if (jDCFecha.getDate() == null)
                {
                    jLFechaNac.setForeground(Color.BLACK);
                } else if (jDCFecha.getDate() != null)
                {
                    jLFechaNac.setForeground(Color.GREEN);

                }
            }
        });
        jPanel1.add(jDCFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 160, -1));

        jLDireccion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLDireccion.setText("Dirección:");
        jPanel1.add(jLDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        jTFDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDireccionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFDireccionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFDireccionKeyTyped(evt);
            }
        });
        jPanel1.add(jTFDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 160, -1));

        jBModifica.setText("Modificar");
        jBModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificaActionPerformed(evt);
            }
        });
        jBModifica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBModificaKeyPressed(evt);
            }
        });
        jPanel1.add(jBModifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 90, -1));

        jPFContra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPFContra1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPFContra1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPFContra1KeyTyped(evt);
            }
        });
        jPanel1.add(jPFContra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 160, -1));

        jLContra2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLContra2.setText("Confirme contraseña:");
        jPanel1.add(jLContra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jPFContra2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPFContra2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPFContra2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPFContra2KeyTyped(evt);
            }
        });
        jPanel1.add(jPFContra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 160, -1));

        jLCedula.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLCedula.setText("Cedula:");
        jLCedula.setEnabled(false);
        jPanel1.add(jLCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        jTFCedula.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFCedula.setEnabled(false);
        jTFCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCedulaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFCedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCedulaKeyTyped(evt);
            }
        });
        jPanel1.add(jTFCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 160, -1));

        jLFacu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLFacu.setText("Facultad de egreso:");
        jLFacu.setEnabled(false);
        jPanel1.add(jLFacu, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));

        jTFFacu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFFacu.setEnabled(false);
        jTFFacu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFFacuKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFFacuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFFacuKeyTyped(evt);
            }
        });
        jPanel1.add(jTFFacu, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLMinimizarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseClicked
    {//GEN-HEADEREND:event_jLMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLMinimizarMouseClicked

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseClicked
    {//GEN-HEADEREND:event_jLCerrarMouseClicked
        Sesion.datosModifica.clear();
        this.dispose();
        new vtnAdminMenuUsuarios().setVisible(true);
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MouseDragged
    {//GEN-HEADEREND:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MousePressed
    {//GEN-HEADEREND:event_jPanel3MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jTFCURPKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCURPKeyTyped
    {//GEN-HEADEREND:event_jTFCURPKeyTyped

        Validaciones.validaAlfanumerico(evt);
        if (jTFCURP.getText().length() == 18) {
            evt.consume();
        }

    }//GEN-LAST:event_jTFCURPKeyTyped

    private void jTFNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreKeyTyped
    {//GEN-HEADEREND:event_jTFNombreKeyTyped
        Validaciones.validaAlfabeticos(evt);
        if (jTFNombre.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFNombreKeyTyped

    private void jTFNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreKeyPressed
    {//GEN-HEADEREND:event_jTFNombreKeyPressed

    }//GEN-LAST:event_jTFNombreKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        CtrlInterfaz.selecciona(jTFTelefono);

        idEmpleado = (String) Sesion.datosModifica.get(0);
        Querys q = new Querys();
        ArrayList<Object> mapeoData = new ArrayList<Object>();
        ArrayList<Object> mapeoData2 = new ArrayList<Object>();

        try {
            mapeoData = q.Seleccion(con, "*", "usuarios", "Id_empleado = " + idEmpleado, false);
        } catch (Exception e) {
            System.out.println("Error al obtener los datos del empelado" + idEmpleado + "..." + e);
        }

        int rolEmpleado = Integer.parseInt(((String) mapeoData.get(11)).trim());

        if (rolEmpleado == 2) {
            try {
                mapeoData2 = q.Seleccion(con, "*", "medicos", "Id_medico = " + idEmpleado, false);
            } catch (Exception e) {
                System.out.println("Error al obtener datos del medico..." + e);
            }

            jTFNombre.setText(((String) mapeoData.get(1)).trim());
            jTFAPaterno.setText(((String) mapeoData.get(2)).trim());
            jTFAMaterno.setText(((String) mapeoData.get(3)).trim());
            jTFTelefono.setText(((String) mapeoData.get(4)).trim());
            jTFEmail.setText(((String) mapeoData.get(5)).trim());
            jPFContra1.setText(((String) mapeoData.get(6)).trim());
            jPFContra2.setText(((String) mapeoData.get(6)).trim());
            jTFCURP.setText(((String) mapeoData.get(7)).trim());

            String sexo = ((String) mapeoData.get(8)).trim();
            if (sexo.equals("Masculino")) {
                jCBSexo.setSelectedIndex(1);
            } else if (sexo.equals("Femenino")) {
                jCBSexo.setSelectedIndex(2);
            }

            try {
                String fechaMap = ((String) mapeoData.get(9)).trim();
                Date fecha1 = new SimpleDateFormat("yyyy-MM-dd").parse(fechaMap);
                jDCFecha.setDate(fecha1);
            } catch (Exception e) {
                System.out.println("Error al comvetir la fecha..." + e);
            }

            jTFDireccion.setText(((String) mapeoData.get(10)).trim());

            int rolMap = Integer.parseInt(((String) mapeoData.get(11)).trim());

            jCBRol.setSelectedIndex(2);

            jTFCedula.setText(((String) mapeoData2.get(2)).trim());
            jTFFacu.setText(((String) mapeoData2.get(3)).trim());

        } else {
            jTFNombre.setText(((String) mapeoData.get(1)).trim());
            jTFAPaterno.setText(((String) mapeoData.get(2)).trim());
            jTFAMaterno.setText(((String) mapeoData.get(3)).trim());
            jTFTelefono.setText(((String) mapeoData.get(4)).trim());
            jTFEmail.setText(((String) mapeoData.get(5)).trim());
            jPFContra1.setText(((String) mapeoData.get(6)).trim());
            jPFContra2.setText(((String) mapeoData.get(6)).trim());
            jTFCURP.setText(((String) mapeoData.get(7)).trim());

            String sexo = ((String) mapeoData.get(8)).trim();
            if (sexo.equals("Masculino")) {
                jCBSexo.setSelectedIndex(1);
            } else if (sexo.equals("Femenino")) {
                jCBSexo.setSelectedIndex(2);
            }

            try {
                String fechaMap = ((String) mapeoData.get(9)).trim();
                Date fecha1 = new SimpleDateFormat("yyyy-MM-dd").parse(fechaMap);
                jDCFecha.setDate(fecha1);
            } catch (Exception e) {
                System.out.println("Error al comvetir la fecha..." + e);
            }

            jTFDireccion.setText(((String) mapeoData.get(10)).trim());

            int rolMap = Integer.parseInt(((String) mapeoData.get(11)).trim());

            if (rolMap == 1) {
                jCBRol.setSelectedIndex(1);
            } else if (rolMap == 3) {
                jCBRol.setSelectedIndex(3);
            }
        }

    }//GEN-LAST:event_formWindowOpened

    private void jTFAPaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFAPaternoKeyPressed
    {//GEN-HEADEREND:event_jTFAPaternoKeyPressed

    }//GEN-LAST:event_jTFAPaternoKeyPressed

    private void jTFAPaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFAPaternoKeyTyped
    {//GEN-HEADEREND:event_jTFAPaternoKeyTyped
        Validaciones.validaAlfabeticos(evt);
        if (jTFAPaterno.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFAPaternoKeyTyped

    private void jTFAMaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFAMaternoKeyPressed
    {//GEN-HEADEREND:event_jTFAMaternoKeyPressed

    }//GEN-LAST:event_jTFAMaternoKeyPressed

    private void jTFAMaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFAMaternoKeyTyped
    {//GEN-HEADEREND:event_jTFAMaternoKeyTyped
        Validaciones.validaAlfabeticos(evt);
        if (jTFAMaterno.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFAMaternoKeyTyped

    private void jTFTelefonoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFTelefonoKeyPressed
    {//GEN-HEADEREND:event_jTFTelefonoKeyPressed

    }//GEN-LAST:event_jTFTelefonoKeyPressed

    private void jTFTelefonoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFTelefonoKeyTyped
    {//GEN-HEADEREND:event_jTFTelefonoKeyTyped
        Validaciones.validaEntero(evt);
        if (jTFTelefono.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFTelefonoKeyTyped

    private void jTFEmailKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFEmailKeyPressed
    {//GEN-HEADEREND:event_jTFEmailKeyPressed

    }//GEN-LAST:event_jTFEmailKeyPressed

    private void jTFEmailKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFEmailKeyTyped
    {//GEN-HEADEREND:event_jTFEmailKeyTyped
        if (jTFEmail.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFEmailKeyTyped

    private void jTFCURPKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCURPKeyPressed
    {//GEN-HEADEREND:event_jTFCURPKeyPressed

    }//GEN-LAST:event_jTFCURPKeyPressed

    private void jCBSexoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jCBSexoKeyPressed
    {//GEN-HEADEREND:event_jCBSexoKeyPressed
        Validaciones.enter(this, evt, jDCFecha);
    }//GEN-LAST:event_jCBSexoKeyPressed

    private void jDCFechaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jDCFechaKeyPressed
    {//GEN-HEADEREND:event_jDCFechaKeyPressed
        Validaciones.enter(this, evt, jTFDireccion);
    }//GEN-LAST:event_jDCFechaKeyPressed

    private void jDCFechaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jDCFechaKeyTyped
    {//GEN-HEADEREND:event_jDCFechaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jDCFechaKeyTyped

    private void jTFDireccionKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFDireccionKeyPressed
    {//GEN-HEADEREND:event_jTFDireccionKeyPressed

    }//GEN-LAST:event_jTFDireccionKeyPressed

    private void jTFDireccionKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFDireccionKeyTyped
    {//GEN-HEADEREND:event_jTFDireccionKeyTyped
        Validaciones.validaAlfanumerico(evt);
        if (jTFDireccion.getText().length() == 180) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFDireccionKeyTyped

    private void jBModificaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jBModificaKeyPressed
    {//GEN-HEADEREND:event_jBModificaKeyPressed
        if (evt.getKeyChar() == '\n') {
            jBModificaActionPerformed(null);
        }
    }//GEN-LAST:event_jBModificaKeyPressed

    private void jBModificaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBModificaActionPerformed
    {//GEN-HEADEREND:event_jBModificaActionPerformed
        Querys q = new Querys();

        if (jLTelefono.getForeground().getRGB() == Color.GREEN.getRGB()
                && jLContra1.getForeground().getRGB() == Color.GREEN.getRGB()
                && jLContra2.getForeground().getRGB() == Color.GREEN.getRGB()
                && jLFechaNac.getForeground().getRGB() == Color.GREEN.getRGB()
                && jLDireccion.getForeground().getRGB() == Color.GREEN.getRGB()) {

            Date fecha1 = jDCFecha.getDate();
            DateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String fecha2 = f.format(fecha1);

            String values = "'" + jTFTelefono.getText() + "',"
                    + "'" + jPFContra2.getText() + "',"
                    + "'" + fecha2 + "',"
                    + "'" + jTFDireccion.getText() + "'";

            String columnas1 = "Telefono,Contrasenia,Fecha_nacimiento,Direccion";

            if (Mensaje.pregunta(this, "¿Estas seguro de modificar el usuario?") == JOptionPane.YES_OPTION) {
                try {
                    q.Modificar(con, "usuarios", columnas1, values, "Id_empleado = " + idEmpleado);
                } catch (Exception e) {
                    System.out.println("Modificacion erronea" + e);
                }

                Mensaje.exito(this, "Se modifico el usuario correctamente");
                Sesion.datosModifica.clear();
                this.dispose();
                new vtnAdminMenuUsuarios().setVisible(true);
            } else {
                Mensaje.error(this, "No se hizo la modificacion");
            }

        } else {
            Mensaje.error(this, "Verifique que todos los campos esten en verde");
        }

    }//GEN-LAST:event_jBModificaActionPerformed

    private void jPFContra1KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPFContra1KeyPressed
    {//GEN-HEADEREND:event_jPFContra1KeyPressed

    }//GEN-LAST:event_jPFContra1KeyPressed

    private void jPFContra2KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPFContra2KeyPressed
    {//GEN-HEADEREND:event_jPFContra2KeyPressed

    }//GEN-LAST:event_jPFContra2KeyPressed

    private void jPFContra1KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPFContra1KeyTyped
    {//GEN-HEADEREND:event_jPFContra1KeyTyped
        if (jPFContra1.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jPFContra1KeyTyped

    private void jPFContra2KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPFContra2KeyTyped
    {//GEN-HEADEREND:event_jPFContra2KeyTyped

        if (jPFContra2.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jPFContra2KeyTyped

    private void jPFContra2KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPFContra2KeyReleased
    {//GEN-HEADEREND:event_jPFContra2KeyReleased
        if (jPFContra2.getText().isEmpty()) {
            jLContra2.setForeground(Color.BLACK);
        } else if (jPFContra2.getText().equals(jPFContra1.getText())) {
            jLContra2.setForeground(Color.GREEN);
            Validaciones.enter(this, evt, jDCFecha);
        } else {
            jLContra2.setForeground(Color.RED);
        }
    }//GEN-LAST:event_jPFContra2KeyReleased

    private void jTFTelefonoKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFTelefonoKeyReleased
    {//GEN-HEADEREND:event_jTFTelefonoKeyReleased
        if (jTFTelefono.getText().isEmpty()) {
            jLTelefono.setForeground(Color.BLACK);
        } else if (jTFTelefono.getText().length() == 10) {
            jLTelefono.setForeground(Color.GREEN);
            Validaciones.enter(this, evt, jPFContra1);
        } else {
            jLTelefono.setForeground(Color.RED);
        }
    }//GEN-LAST:event_jTFTelefonoKeyReleased

    private void formWindowStateChanged(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowStateChanged
    {//GEN-HEADEREND:event_formWindowStateChanged

    }//GEN-LAST:event_formWindowStateChanged

    private void jTFNombreKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreKeyReleased
    {//GEN-HEADEREND:event_jTFNombreKeyReleased
        if (jTFNombre.getText().isEmpty()) {
            jLNombre.setForeground(Color.BLACK);
        } else {
            jLNombre.setForeground(Color.GREEN);
            Validaciones.enter(this, evt, jTFAPaterno);
        }
    }//GEN-LAST:event_jTFNombreKeyReleased

    private void jTFAPaternoKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFAPaternoKeyReleased
    {//GEN-HEADEREND:event_jTFAPaternoKeyReleased
        if (jTFAPaterno.getText().isEmpty()) {
            jLAPaterno.setForeground(Color.BLACK);
        } else {
            Validaciones.enter(this, evt, jTFAMaterno);
            jLAPaterno.setForeground(Color.GREEN);
        }
    }//GEN-LAST:event_jTFAPaternoKeyReleased

    private void jTFAMaternoKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFAMaternoKeyReleased
    {//GEN-HEADEREND:event_jTFAMaternoKeyReleased

        if (jTFAMaterno.getText().isEmpty()) {
            jLAMaterno.setForeground(Color.BLACK);
        } else {
            Validaciones.enter(this, evt, jTFTelefono);
            jLAMaterno.setForeground(Color.GREEN);
        }
    }//GEN-LAST:event_jTFAMaternoKeyReleased

    private void jTFEmailKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFEmailKeyReleased
    {//GEN-HEADEREND:event_jTFEmailKeyReleased
        ArrayList<Object> consultaEmail = new ArrayList<Object>();;
        Querys q = new Querys();
        try {
            consultaEmail = q.Seleccion(con, "Email", "usuarios", "Email='" + jTFEmail.getText() + "'", true);

        } catch (Exception e) {
            System.out.println("Error: exception ->" + e);
        }
        if (jTFEmail.getText().isEmpty()) {
            jLEmail.setForeground(Color.BLACK);
        } else if (jTFEmail.getText().matches("^[^@]+@[^@]+\\.[a-zA-Z]{2,}$")) {
            Validaciones.enter(this, evt, jPFContra1);
            jLEmail.setForeground(Color.GREEN);
        } else {
            jLEmail.setForeground(Color.RED);
        }
        try {

            if (consultaEmail.get(0).equals(jTFEmail.getText())) {
                jLEmail.setForeground(Color.YELLOW);
            }

        } catch (Exception e) {
            System.out.println("no encontro resultado al mail aun-->" + e);
        }

    }//GEN-LAST:event_jTFEmailKeyReleased

    private void jPFContra1KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPFContra1KeyReleased
    {//GEN-HEADEREND:event_jPFContra1KeyReleased
        if (jPFContra1.getText().isEmpty()) {
            jLContra1.setForeground(Color.BLACK);
        } else if (jPFContra1.getText().length() >= 8) {
            jLContra1.setForeground(Color.GREEN);
            Validaciones.enter(this, evt, jPFContra2);
        } else {
            jLContra1.setForeground(Color.RED);
        }
    }//GEN-LAST:event_jPFContra1KeyReleased

    private void jTFCURPKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCURPKeyReleased
    {//GEN-HEADEREND:event_jTFCURPKeyReleased
        ArrayList<Object> consultaCURP = new ArrayList<Object>();
        Querys q = new Querys();

        try {
            consultaCURP = q.Seleccion(con, "CURP", "usuarios", "CURP='" + jTFCURP.getText() + "'", true);

        } catch (Exception e) {
            System.out.println("Error: exception ->" + e);
        }

        if (jTFCURP.getText().isEmpty()) {
            jLCURP.setForeground(Color.BLACK);
        } else if (jTFCURP.getText().length() == 18) {
            jLCURP.setForeground(Color.GREEN);
            Validaciones.enter(this, evt, jCBSexo);
        } else {
            jLCURP.setForeground(Color.RED);
        }

        try {

            if (consultaCURP.get(0).equals(jTFCURP.getText())) {
                jLCURP.setForeground(Color.YELLOW);
            }

        } catch (Exception e) {
            System.out.println("no encontro resultado el curp aun-->" + e);
        }
    }//GEN-LAST:event_jTFCURPKeyReleased

    private void jCBSexoKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jCBSexoKeyReleased
    {//GEN-HEADEREND:event_jCBSexoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBSexoKeyReleased

    private void jCBSexoMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jCBSexoMouseReleased
    {//GEN-HEADEREND:event_jCBSexoMouseReleased

    }//GEN-LAST:event_jCBSexoMouseReleased

    private void jCBSexoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jCBSexoMouseClicked
    {//GEN-HEADEREND:event_jCBSexoMouseClicked

    }//GEN-LAST:event_jCBSexoMouseClicked

    private void jCBSexoMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jCBSexoMousePressed
    {//GEN-HEADEREND:event_jCBSexoMousePressed

    }//GEN-LAST:event_jCBSexoMousePressed

    private void jCBSexoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jCBSexoItemStateChanged
    {//GEN-HEADEREND:event_jCBSexoItemStateChanged

    }//GEN-LAST:event_jCBSexoItemStateChanged

    private void jDCFechaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jDCFechaKeyReleased
    {//GEN-HEADEREND:event_jDCFechaKeyReleased

    }//GEN-LAST:event_jDCFechaKeyReleased

    private void none(java.awt.event.InputMethodEvent evt)//GEN-FIRST:event_none
    {//GEN-HEADEREND:event_none

    }//GEN-LAST:event_none

    private void jDCFechaPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_jDCFechaPropertyChange
    {//GEN-HEADEREND:event_jDCFechaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDCFechaPropertyChange

    private void jDCFechaCaretPositionChanged(java.awt.event.InputMethodEvent evt)//GEN-FIRST:event_jDCFechaCaretPositionChanged
    {//GEN-HEADEREND:event_jDCFechaCaretPositionChanged

    }//GEN-LAST:event_jDCFechaCaretPositionChanged

    private void jDCFechaMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jDCFechaMouseExited
    {//GEN-HEADEREND:event_jDCFechaMouseExited

    }//GEN-LAST:event_jDCFechaMouseExited

    private void jDCFechaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jDCFechaMouseClicked
    {//GEN-HEADEREND:event_jDCFechaMouseClicked

    }//GEN-LAST:event_jDCFechaMouseClicked

    private void jTFDireccionKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFDireccionKeyReleased
    {//GEN-HEADEREND:event_jTFDireccionKeyReleased
        if (jTFDireccion.getText().isEmpty()) {
            jLDireccion.setForeground(Color.BLACK);
        } else {
            Validaciones.enter(this, evt, jBModifica);
            jLDireccion.setForeground(Color.GREEN);
        }
    }//GEN-LAST:event_jTFDireccionKeyReleased

    private void jCBRolItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jCBRolItemStateChanged
    {//GEN-HEADEREND:event_jCBRolItemStateChanged

    }//GEN-LAST:event_jCBRolItemStateChanged

    private void jCBRolMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jCBRolMouseClicked
    {//GEN-HEADEREND:event_jCBRolMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBRolMouseClicked

    private void jCBRolMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jCBRolMousePressed
    {//GEN-HEADEREND:event_jCBRolMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBRolMousePressed

    private void jCBRolMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jCBRolMouseReleased
    {//GEN-HEADEREND:event_jCBRolMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBRolMouseReleased

    private void jCBRolKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jCBRolKeyPressed
    {//GEN-HEADEREND:event_jCBRolKeyPressed
        Validaciones.enter(this, evt, jBModifica);
    }//GEN-LAST:event_jCBRolKeyPressed

    private void jCBRolKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jCBRolKeyReleased
    {//GEN-HEADEREND:event_jCBRolKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBRolKeyReleased

    private void jTFCURPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTFCURPActionPerformed
    {//GEN-HEADEREND:event_jTFCURPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCURPActionPerformed

    private void jTFCedulaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCedulaKeyPressed
    {//GEN-HEADEREND:event_jTFCedulaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCedulaKeyPressed

    private void jTFCedulaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCedulaKeyReleased
    {//GEN-HEADEREND:event_jTFCedulaKeyReleased
        if (jTFCedula.getText().isEmpty()) {
            jLCedula.setForeground(Color.BLACK);
        } else if (jTFCedula.getText().length() == 8) {
            jLCedula.setForeground(Color.GREEN);
            Validaciones.enter(this, evt, jTFFacu);
        } else {
            jLCedula.setForeground(Color.RED);
        }
    }//GEN-LAST:event_jTFCedulaKeyReleased

    private void jTFCedulaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFCedulaKeyTyped
    {//GEN-HEADEREND:event_jTFCedulaKeyTyped
        Validaciones.validaAlfanumerico(evt);
        if (jTFCedula.getText().length() == 8) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFCedulaKeyTyped

    private void jTFFacuKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFFacuKeyPressed
    {//GEN-HEADEREND:event_jTFFacuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFFacuKeyPressed

    private void jTFFacuKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFFacuKeyReleased
    {//GEN-HEADEREND:event_jTFFacuKeyReleased
        if (jTFFacu.getText().isEmpty()) {
            jLFacu.setForeground(Color.BLACK);
        } else {
            jLFacu.setForeground(Color.GREEN);
            Validaciones.enter(this, evt, jBModifica);
        }
    }//GEN-LAST:event_jTFFacuKeyReleased

    private void jTFFacuKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFFacuKeyTyped
    {//GEN-HEADEREND:event_jTFFacuKeyTyped
        Validaciones.validaAlfanumerico(evt);
        if (jTFFacu.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFFacuKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMenuUsuariosM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMenuUsuariosM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMenuUsuariosM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnAdminMenuUsuariosM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnAdminMenuUsuariosM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBModifica;
    private javax.swing.JComboBox<String> jCBRol;
    private javax.swing.JComboBox<String> jCBSexo;
    private com.toedter.calendar.JDateChooser jDCFecha;
    private javax.swing.JLabel jLAMaterno;
    private javax.swing.JLabel jLAPaterno;
    private javax.swing.JLabel jLCURP;
    private javax.swing.JLabel jLCedula;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLContra1;
    private javax.swing.JLabel jLContra2;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLFacu;
    private javax.swing.JLabel jLFechaNac;
    private javax.swing.JLabel jLMinimizar;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLRol;
    private javax.swing.JLabel jLSexo;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JLabel jLTitulo1;
    private javax.swing.JPasswordField jPFContra1;
    private javax.swing.JPasswordField jPFContra2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTFAMaterno;
    private javax.swing.JTextField jTFAPaterno;
    private javax.swing.JTextField jTFCURP;
    private javax.swing.JTextField jTFCedula;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFFacu;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFTelefono;
    // End of variables declaration//GEN-END:variables
}
