/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bd.Querys;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import static interfaces.vtnLogin.con;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.StyledEditorKit;

/**
 *
 * @author david
 */
public class vtnAdminAM extends javax.swing.JFrame
{

    int xy, xx;
    boolean flagMedico = false;

    /**
     * Creates new form vtnAdminAU
     */
    public vtnAdminAM()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel3 = new javax.swing.JPanel();
        jLMinimizar = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLTitulo1 = new javax.swing.JLabel();
        jLNombreG = new javax.swing.JLabel();
        jTFNombreG = new javax.swing.JTextField();
        jLNombreC = new javax.swing.JLabel();
        jTFNombreC = new javax.swing.JTextField();
        jLContenido = new javax.swing.JLabel();
        jTFContenido = new javax.swing.JTextField();
        jLVia = new javax.swing.JLabel();
        jTFVia = new javax.swing.JTextField();
        jLRecip = new javax.swing.JLabel();
        jTFRecip = new javax.swing.JTextField();
        jLLab = new javax.swing.JLabel();
        jTFLab = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowStateListener(new java.awt.event.WindowStateListener()
        {
            public void windowStateChanged(java.awt.event.WindowEvent evt)
            {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 35));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/minimizar-icon.png"))); // NOI18N
        jLMinimizar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMouseClicked(evt);
            }
        });
        jPanel3.add(jLMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, 40));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/regreso.png"))); // NOI18N
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLCerrarMouseClicked(evt);
            }
        });
        jPanel3.add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 30, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLTitulo1.setText("Alta de productos");
        jPanel2.add(jLTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLNombreG.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLNombreG.setText("Nombre generico:");
        jPanel2.add(jLNombreG, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jTFNombreG.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFNombreG.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFNombreGKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTFNombreGKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFNombreGKeyTyped(evt);
            }
        });
        jPanel2.add(jTFNombreG, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 160, -1));

        jLNombreC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLNombreC.setText("Nombre comercial:");
        jPanel2.add(jLNombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jTFNombreC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFNombreC.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFNombreCKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTFNombreCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFNombreCKeyTyped(evt);
            }
        });
        jPanel2.add(jTFNombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, -1));

        jLContenido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLContenido.setText("Contenido:");
        jPanel2.add(jLContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jTFContenido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFContenido.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFContenidoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTFContenidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFContenidoKeyTyped(evt);
            }
        });
        jPanel2.add(jTFContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 160, -1));

        jLVia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLVia.setText("Via de administración:");
        jPanel2.add(jLVia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jTFVia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFVia.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFViaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTFViaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFViaKeyTyped(evt);
            }
        });
        jPanel2.add(jTFVia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 160, -1));

        jLRecip.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLRecip.setText("Recipiente:");
        jPanel2.add(jLRecip, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jTFRecip.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFRecip.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFRecipKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTFRecipKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFRecipKeyTyped(evt);
            }
        });
        jPanel2.add(jTFRecip, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 160, -1));

        jLLab.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLLab.setText("Laboratorio:");
        jPanel2.add(jLLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jTFLab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFLab.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jTFLabKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTFLabKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTFLabKeyTyped(evt);
            }
        });
        jPanel2.add(jTFLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 160, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLMinimizarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseClicked
    {//GEN-HEADEREND:event_jLMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLMinimizarMouseClicked

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseClicked
    {//GEN-HEADEREND:event_jLCerrarMouseClicked
        this.dispose();
        new vtnAdminBCU().setVisible(true);
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MouseDragged
    {//GEN-HEADEREND:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MousePressed
    {//GEN-HEADEREND:event_jPanel3MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        CtrlInterfaz.selecciona(jTFNombreG);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowStateChanged(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowStateChanged
    {//GEN-HEADEREND:event_formWindowStateChanged

    }//GEN-LAST:event_formWindowStateChanged

    private void jTFNombreGKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreGKeyPressed
    {//GEN-HEADEREND:event_jTFNombreGKeyPressed

    }//GEN-LAST:event_jTFNombreGKeyPressed

    private void jTFNombreGKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreGKeyReleased
    {//GEN-HEADEREND:event_jTFNombreGKeyReleased
        if (jTFNombreG.getText().isEmpty())
        {
            jLNombreG.setForeground(Color.BLACK);
        } else
        {
            jLNombreG.setForeground(Color.GREEN);
            Validaciones.enter(this, evt, jTFNombreC);
        }
    }//GEN-LAST:event_jTFNombreGKeyReleased

    private void jTFNombreGKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreGKeyTyped
    {//GEN-HEADEREND:event_jTFNombreGKeyTyped
        Validaciones.validaAlfabeticos(evt);
        if (jTFNombreG.getText().length() == 30)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTFNombreGKeyTyped

    private void jTFNombreCKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreCKeyPressed
    {//GEN-HEADEREND:event_jTFNombreCKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreCKeyPressed

    private void jTFNombreCKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreCKeyReleased
    {//GEN-HEADEREND:event_jTFNombreCKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreCKeyReleased

    private void jTFNombreCKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFNombreCKeyTyped
    {//GEN-HEADEREND:event_jTFNombreCKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreCKeyTyped

    private void jTFContenidoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFContenidoKeyPressed
    {//GEN-HEADEREND:event_jTFContenidoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFContenidoKeyPressed

    private void jTFContenidoKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFContenidoKeyReleased
    {//GEN-HEADEREND:event_jTFContenidoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFContenidoKeyReleased

    private void jTFContenidoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFContenidoKeyTyped
    {//GEN-HEADEREND:event_jTFContenidoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFContenidoKeyTyped

    private void jTFViaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFViaKeyPressed
    {//GEN-HEADEREND:event_jTFViaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFViaKeyPressed

    private void jTFViaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFViaKeyReleased
    {//GEN-HEADEREND:event_jTFViaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFViaKeyReleased

    private void jTFViaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFViaKeyTyped
    {//GEN-HEADEREND:event_jTFViaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFViaKeyTyped

    private void jTFRecipKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFRecipKeyPressed
    {//GEN-HEADEREND:event_jTFRecipKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFRecipKeyPressed

    private void jTFRecipKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFRecipKeyReleased
    {//GEN-HEADEREND:event_jTFRecipKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFRecipKeyReleased

    private void jTFRecipKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFRecipKeyTyped
    {//GEN-HEADEREND:event_jTFRecipKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFRecipKeyTyped

    private void jTFLabKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFLabKeyPressed
    {//GEN-HEADEREND:event_jTFLabKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFLabKeyPressed

    private void jTFLabKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFLabKeyReleased
    {//GEN-HEADEREND:event_jTFLabKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFLabKeyReleased

    private void jTFLabKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTFLabKeyTyped
    {//GEN-HEADEREND:event_jTFLabKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFLabKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(vtnAdminAM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(vtnAdminAM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(vtnAdminAM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(vtnAdminAM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new vtnAdminAM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLContenido;
    private javax.swing.JLabel jLLab;
    private javax.swing.JLabel jLMinimizar;
    private javax.swing.JLabel jLNombreC;
    private javax.swing.JLabel jLNombreG;
    private javax.swing.JLabel jLRecip;
    private javax.swing.JLabel jLTitulo1;
    private javax.swing.JLabel jLVia;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTFContenido;
    private javax.swing.JTextField jTFLab;
    private javax.swing.JTextField jTFNombreC;
    private javax.swing.JTextField jTFNombreG;
    private javax.swing.JTextField jTFRecip;
    private javax.swing.JTextField jTFVia;
    // End of variables declaration//GEN-END:variables
}
