/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import bd.Querys;
import bd.Sesion;
import cjb.ci.Mensaje;
import static interfaces.vtnLogin.con;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class vtnAdminBCU extends javax.swing.JFrame
{

    int xy, xx;
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form vtnAdminAU
     */
    public vtnAdminBCU()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel3 = new javax.swing.JPanel();
        jLMinimizar = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLTitulo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsers = new javax.swing.JTable();
        jBNewUser = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 35));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/minimizar-icon.png"))); // NOI18N
        jLMinimizar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLMinimizarMouseClicked(evt);
            }
        });
        jPanel3.add(jLMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, 40));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/regreso.png"))); // NOI18N
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLCerrarMouseClicked(evt);
            }
        });
        jPanel3.add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 30, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLTitulo1.setText("Administración de usuarios");
        jPanel1.add(jLTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jTUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTUsers);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 510, 360));

        jBNewUser.setText("Nuevo usuario");
        jBNewUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBNewUserActionPerformed(evt);
            }
        });
        jPanel1.add(jBNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 140, -1));

        jBEliminar.setText("Eliminar usuario");
        jBEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 140, -1));

        jBModificar.setText("Modificar usuario");
        jBModificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLMinimizarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLMinimizarMouseClicked
    {//GEN-HEADEREND:event_jLMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLMinimizarMouseClicked

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLCerrarMouseClicked
    {//GEN-HEADEREND:event_jLCerrarMouseClicked
        this.dispose();
        new vtnMainAdmin().setVisible(true);
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MouseDragged
    {//GEN-HEADEREND:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MousePressed
    {//GEN-HEADEREND:event_jPanel3MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jBNewUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBNewUserActionPerformed
    {//GEN-HEADEREND:event_jBNewUserActionPerformed
        this.dispose();
        new vtnAdminAU().setVisible(true);
    }//GEN-LAST:event_jBNewUserActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        CrearModelo();
        llenaTabla();
    }//GEN-LAST:event_formWindowOpened

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBEliminarActionPerformed
    {//GEN-HEADEREND:event_jBEliminarActionPerformed

        if (jTUsers.getSelectedRow() == -1)
        {
            Mensaje.error(this, "No hay valores seleccionados en la tabla");
        } else
        {
            int row = jTUsers.getSelectedRow();
            String idEmpleado = (String) jTUsers.getValueAt(row, 0);
            String name = (String) jTUsers.getValueAt(row, 1);
            String aP = (String) jTUsers.getValueAt(row, 2);
            String aM = (String) jTUsers.getValueAt(row, 3);
            String email = (String) jTUsers.getValueAt(row, 4);
            String rol = (String) jTUsers.getValueAt(row, 5);

            if (rol.equals("Médico"))
            {
                Querys q = new Querys();
                ArrayList<Object> id = new ArrayList<Object>();

                if (Mensaje.pregunta(this, "¿Estas seguro de eliminar al usuario?") == JOptionPane.YES_OPTION)
                {
                    try
                    {
                        q.Delete(con, "medicos", "Id_medico", idEmpleado);

                        q.Delete(con, "usuarios", "Id_empleado", idEmpleado);
                    } catch (Exception e)
                    {
                        System.out.println("Error al eliminar... " + e);
                    }

                    Mensaje.exito(this, "Se elimino el usuario correctamente");

                    int rowCount = modelo.getRowCount();
                    for (int i = rowCount - 1; i >= 0; i--)
                    {
                        modelo.removeRow(i);
                    }
                    formWindowOpened(null);
                } else
                {
                    Mensaje.error(this, "No se elimino ningun usuario");
                }

            } else
            {
                Querys q = new Querys();
                ArrayList<Object> id = new ArrayList<Object>();

                if (Mensaje.pregunta(this, "¿Estas seguro de eliminar al usuario?") == JOptionPane.YES_OPTION)
                {
                    try
                    {
                        q.Delete(con, "usuarios", "Id_empleado", idEmpleado);
                    } catch (Exception e)
                    {
                        System.out.println("Error al eliminar... " + e);
                    }

                    Mensaje.exito(this, "Se elimino el usuario correctamente");
                    int rowCount = modelo.getRowCount();
                    for (int i = rowCount - 1; i >= 0; i--)
                    {
                        modelo.removeRow(i);
                    }
                    formWindowOpened(null);
                } else
                {
                    Mensaje.error(this, "No se elimino ningun usuario");
                }
            }

            System.out.println(idEmpleado + name + aP + aM + email + rol);
        }


    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel1MouseClicked
    {//GEN-HEADEREND:event_jPanel1MouseClicked
        jTUsers.clearSelection();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBModificarActionPerformed
    {//GEN-HEADEREND:event_jBModificarActionPerformed
        if (jTUsers.getSelectedRow() == -1)
        {
            Mensaje.error(this, "No hay valores seleccionados en la tabla");
        } else
        {
            int row = jTUsers.getSelectedRow();
            String idEmpleado = (String) jTUsers.getValueAt(row, 0);
            Sesion.datosModifica.add(idEmpleado);
            this.dispose();
            new vtnAdminMU().setVisible(true);
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void CrearModelo()
    {
        try
        {
            modelo = (new DefaultTableModel(
                    null, new String[]
                    {
                        "ID Empleado", "Nombre", "Apellido Paterno", "Apellido Materno", "Email", "Rol"
                    })
            {
                Class[] types = new Class[]
                {
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                    java.lang.Object.class,
                };
                boolean[] canEdit = new boolean[]
                {
                    false, false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex)
                {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex)
                {
                    return canEdit[colIndex];
                }
            });
            jTUsers.setModel(modelo);

        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.toString() + "error en la creacion del modelo");
        }
    }

    public void llenaTabla()
    {
        ArrayList<Object> mapeoUsers = new ArrayList<Object>();
        Querys q = new Querys();
        modelo.setRowCount(0);
        try
        {
            mapeoUsers = q.Seleccion(con, "*", "usuarios", "Email!='" + Sesion.datosUsuario.get(5) + "' AND Id_empleado!=1", true);

            Object[] filas = new Object[6];

            while (!mapeoUsers.isEmpty())
            {

                filas[0] = mapeoUsers.get(0);
                filas[1] = mapeoUsers.get(1);
                filas[2] = mapeoUsers.get(2);
                filas[3] = mapeoUsers.get(3);
                filas[4] = mapeoUsers.get(5);

                if (mapeoUsers.get(11).equals("1"))
                {
                    filas[5] = "Administrador";
                } else if (mapeoUsers.get(11).equals("2"))
                {
                    filas[5] = "Médico";
                } else if (mapeoUsers.get(11).equals("3"))
                {
                    filas[5] = "Auxiliar";
                }

                for (int i = 0; i < 12; i++)
                {
                    mapeoUsers.remove(0);
                }
                modelo.addRow(filas);
            }

        } catch (Exception e)
        {
            System.out.println("Error en el llenado de la tabla: " + e.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(vtnAdminBCU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(vtnAdminBCU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(vtnAdminBCU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(vtnAdminBCU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new vtnAdminBCU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNewUser;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLMinimizar;
    private javax.swing.JLabel jLTitulo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTUsers;
    // End of variables declaration//GEN-END:variables
}
