/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import cjb.ci.*;
import java.util.ArrayList;
import bd.*;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import controladores.cambioColor;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.System.exit;
import java.sql.Connection;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author david
 */
public class vtnLogin extends javax.swing.JFrame {

    int xy, xx;
    static Connection con = null;
    public static boolean flag;
    public ArrayList<Object> consulta1 = new ArrayList<Object>();
    Querys q;
    cambioColor cc = new cambioColor();

    /**
     * Creates new form vtnLogin
     */
    public vtnLogin() {
        initComponents();
        jPOverlay.setBackground(new Color(0, 50, 100, 100));//Hace el panel transparente
        
        Image icono = Toolkit.getDefaultToolkit().getImage("src/design/softipet.png");
        this.setIconImage(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLLogo = new javax.swing.JPanel();
        jBIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPContra = new javax.swing.JPanel();
        jPFContra = new javax.swing.JPasswordField();
        jLContrasena = new javax.swing.JLabel();
        jPCorreo = new javax.swing.JPanel();
        jTFCorreo = new javax.swing.JTextField();
        jLCorreo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPOverlay = new javax.swing.JPanel();
        jLBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login SOFTIPET");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBIniciar.setBackground(new java.awt.Color(102, 204, 255));
        jBIniciar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jBIniciar.setText("Inicia sesión");
        jBIniciar.setBorder(null);
        jBIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIniciarActionPerformed(evt);
            }
        });
        jBIniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBIniciarKeyPressed(evt);
            }
        });
        jLLogo.add(jBIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 100, 20));

        jLabel1.setText("Copyright 2020 por ViVeSoft");
        jLLogo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jPContra.setBackground(new java.awt.Color(255, 255, 255));
        jPContra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPContra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPFContra.setBorder(null);
        jPFContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPFContraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPFContraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPFContraKeyTyped(evt);
            }
        });
        jPContra.add(jPFContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 20));

        jLContrasena.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLContrasena.setText("Contraseña:");
        jPContra.add(jLContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLLogo.add(jPContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 210, 50));

        jPCorreo.setBackground(new java.awt.Color(255, 255, 255));
        jPCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPCorreo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFCorreo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTFCorreo.setAlignmentX(2.0F);
        jTFCorreo.setAlignmentY(2.0F);
        jTFCorreo.setBorder(null);
        jTFCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCorreoActionPerformed(evt);
            }
        });
        jTFCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCorreoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFCorreoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCorreoKeyTyped(evt);
            }
        });
        jPCorreo.add(jTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 20));

        jLCorreo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLCorreo.setText("Correo:");
        jPCorreo.add(jLCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLLogo.add(jPCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 210, 50));

        jLabel2.setText("Version Oficial 1.6");
        jLLogo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/softipet.png"))); // NOI18N
        jLLogo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 90, 90));

        getContentPane().add(jLLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 380, 400));

        jPOverlay.setPreferredSize(new java.awt.Dimension(350, 400));
        jPOverlay.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPOverlayMouseDragged(evt);
            }
        });
        jPOverlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/log-background.jpg"))); // NOI18N
        jPOverlay.add(jLBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        getContentPane().add(jPOverlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPOverlayMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPOverlayMouseDragged
    {//GEN-HEADEREND:event_jPOverlayMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPOverlayMouseDragged

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        con = ConectarBase.conectaBD();

        if (flag) {
            System.out.println("Se conecto correctamente a la BD");
        } else {
            Mensaje.error(this, "Error con la conexion a la BD, verifica tu conexion.");
            this.dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jPFContraKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPFContraKeyTyped
    {//GEN-HEADEREND:event_jPFContraKeyTyped
        Validaciones.validaAlfanumerico(evt);
    }//GEN-LAST:event_jPFContraKeyTyped

    private void jPFContraKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPFContraKeyPressed
    {//GEN-HEADEREND:event_jPFContraKeyPressed
        jBIniciarKeyPressed(evt);
    }//GEN-LAST:event_jPFContraKeyPressed

    private void jBIniciarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBIniciarActionPerformed
    {//GEN-HEADEREND:event_jBIniciarActionPerformed
        q = new Querys();
        try {
            consulta1 = q.Seleccion(con, "*", "usuarios", "Email='" + jTFCorreo.getText() + "'", true);

        } catch (Exception e) {
            System.out.println("Error: exception ->" + e);
        }

        if (consulta1.isEmpty()) {
            Mensaje.error(this, "El correo ingresado no existe\nCapture un correo valido");
            clean();
            CtrlInterfaz.selecciona(jTFCorreo);
        } else {
            if (consulta1.get(6).equals(jPFContra.getText())) {
                System.out.println("Password correcto");

                if (consulta1.get(11).equals("1")) {
                    Sesion.datosUsuario = consulta1;
                    new vtnAdminMenu().setVisible(true);
                    this.dispose();
                    Mensaje.exito(this, "Se inicio sesión correctamente");
                }
                if (consulta1.get(11).equals("2")) {
                    Sesion.datosUsuario = consulta1;
                    new vtnMedicoMenu().setVisible(true);
                    this.dispose();
                    Mensaje.exito(this, "Se inicio sesión correctamente");
                }
                if (consulta1.get(11).equals("3")) {
                    Sesion.datosUsuario = consulta1;
                    new vtnEmpleadoMenu().setVisible(true);
                    this.dispose();
                    Mensaje.exito(this, "Se inicio sesión correctamente");
                }
            } else {
                Mensaje.error(this, "La contraseña ingresada es erronea\nCapture una contraseña valida");
                CtrlInterfaz.selecciona(jPFContra);
                jPContra.setBackground(new Color(240, 128, 128));
                jLContrasena.setForeground(new Color(123, 36, 28));
                jPFContra.setBackground(new Color(240, 128, 128));
                jPFContra.setForeground(new Color(123, 36, 28));
                jPContra.setBorder(BorderFactory.createLineBorder(new Color(123, 36, 28)));

            }
        }
    }//GEN-LAST:event_jBIniciarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        ConectarBase.desconectaBD(con);
    }//GEN-LAST:event_formWindowClosed

    private void jBIniciarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jBIniciarKeyPressed
    {//GEN-HEADEREND:event_jBIniciarKeyPressed
        if (evt.getKeyChar() == '\n') {
            jBIniciarActionPerformed(null);
        }
    }//GEN-LAST:event_jBIniciarKeyPressed

    private void jTFCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCorreoActionPerformed

    private void jTFCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCorreoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCorreoKeyPressed

    private void jTFCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCorreoKeyTyped

    private void jTFCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCorreoKeyReleased

        if (jTFCorreo.getText().isEmpty()) {
            cc.cDefault(jPCorreo, jLCorreo, jTFCorreo);
        } else if (jTFCorreo.getText().matches("^[^@]+@[^@]+\\.[a-zA-Z]{2,}$")) {
            Validaciones.enter(this, evt, jPFContra);
            cc.cAzul(jPCorreo, jLCorreo, jTFCorreo);
        } else {
            cc.cRojo(jPCorreo, jLCorreo, jTFCorreo);
        }
    }//GEN-LAST:event_jTFCorreoKeyReleased

    private void jPFContraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFContraKeyReleased
        if (jPFContra.getText().isEmpty()) {
            cc.cDefault(jPContra, jPFContra, jLContrasena);
        } else {
            cc.cDefault(jPContra, jPFContra, jLContrasena);
        }
    }//GEN-LAST:event_jPFContraKeyReleased

    public void clean() {
        CtrlInterfaz.limpia(jTFCorreo, jPFContra);
        CtrlInterfaz.selecciona(jTFCorreo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            UIManager.put("Button.arc", 0);
            UIManager.put("Component.arc", 0);
            UIManager.put("CheckBox.arc", 0);
            UIManager.put("ProgressBar.arc", 0);
            vtnLogin.setDefaultLookAndFeelDecorated(true);
            vtnLogin.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIniciar;
    private javax.swing.JLabel jLBackground;
    private javax.swing.JLabel jLContrasena;
    private javax.swing.JLabel jLCorreo;
    private javax.swing.JPanel jLLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPContra;
    private javax.swing.JPanel jPCorreo;
    private javax.swing.JPasswordField jPFContra;
    private javax.swing.JPanel jPOverlay;
    private javax.swing.JTextField jTFCorreo;
    // End of variables declaration//GEN-END:variables
}
